/* ============================================================
   Yappy Cards — les paquets de questions
   ------------------------------------------------------------
   Un paquet par catégorie. Pour ajouter une question, il suffit
   d'ajouter une ligne dans le tableau du bon paquet.

   Deux écritures possibles, mélangeables :

     "Une question toute simple."
     { theme: "Argent", text: "Une question avec son propre libellé." }

   Sans « theme », la carte affiche le nom de la catégorie.
   L'ordre n'a pas d'importance pour le jeu : chaque paquet est
   mélangé au chargement de la page. Il est tenu mélangé ici pour
   qu'on puisse relire le paquet sans lire dix questions d'affilée
   sur le même sujet.

   Les espaces fines avant ? ! : ; sont ajoutées automatiquement
   à l'affichage — inutile de s'en occuper ici.
   ============================================================ */

window.YAPPY_DECKS = {

  warmup: {
    label: "Warm up",
    tagline: "On commence par le commencement.",
    questions: [
      "Quelle petite chose suffit presque toujours à te mettre de bonne humeur ?",
      "Quelle histoire te concernant tes proches adorent raconter ?",
      "Tu préfères être très doué dans un domaine que personne ne valorise, ou moyen dans un domaine très reconnu ?",
      "Sur quoi es-tu étonnamment difficile ?",
      "Quelle question aimerais-tu qu'on te pose plus souvent ?",
      "Quel est le plus gros changement que tu aimerais voir dans ta vie d'ici un an ?",
      "Quel moment récent t'a fait penser : « putain, j'aime bien ma vie » ?",
      "Tu préfères ne plus jamais voyager ou ne plus jamais pouvoir déménager ?",
      "Quelle habitude chez toi ferait rire quelqu'un qui vivrait avec toi ?",
      "Tu préfères envoyer un nude à la mauvaise personne, ou en recevoir un que tu n'avais absolument pas demandé ?",
      "Sur quoi as-tu changé d'avis récemment ?",
      "Quel conseil donnes-tu souvent aux autres, mais ne t'appliques pas toujours à toi-même ?",
      "Qu'est-ce qui te fait te sentir unique ?",
      "Quel est ton petit kiff du moment ?",
      "Tu préfères coucher avec quelqu'un que tu détestes mais qui t'attire à fond, ou quelqu'un que tu adores mais qui ne t'attire pas du tout ?",
      "Quelle première impression les gens ont souvent de toi et qui est fausse ?",
      "Si tu pouvais enlever une seule contrainte de ta vie actuelle, laquelle ?"
    ]
  },

  deep: {
    label: "Deep",
    tagline: "Pour aller là où on ne va pas d'habitude.",
    questions: [
      "Avec qui te sens-tu 100 % toi-même (ou presque) ?",
      "Quel est le plus gros mensonge que tu te racontes actuellement ?",
      "Quelle partie de ta personnalité as-tu construite pour être aimé·e ?",
      "Qu'est-ce que tu prétends ne pas vouloir alors qu'au fond tu le veux énormément ?",
      "Ton partenaire doit-il forcément bien s'entendre avec tes amis ?",
      "Si tu retirais ton métier, tes relations et tes accomplissements, qu'est-ce qui resterait de ton identité ?",
      "Quelle vérité sur toi tu as pris le plus de temps à accepter ?",
      "Qu'est-ce que tu aimerais avoir le courage de dire à quelqu'un ?",
      "À quel moment de ta vie t'es-tu senti le plus perdu ?",
      "Est-ce que tu préférerais connaître ton futur ou pouvoir changer ton passé ?",
      "Quel événement t'a le plus changé ?",
      "Quelle critique te touche beaucoup plus qu'elle ne devrait ?",
      "Que penses-tu du polyamour ?",
      "Quelle est ta dernière fierté ?",
      "Quelle peur influence le plus tes décisions ?",
      "Dans quelle situation tu ne te reconnais plus ?",
      "Dans quelles situations as-tu tendance à devenir quelqu'un que tu aimes moins ?",
      "Tu penses que tu es plus dur·e avec toi-même ou avec les autres ?",
      "Qu'est-ce que tu veux que tes proches disent de toi quand tu n'es pas là ?",
      "Qu'est-ce que tu as longtemps considéré comme un défaut et que tu commences à voir comme une force ?",
      "Dois-tu des excuses à quelqu'un ? Pourquoi ?",
      "Qu'est-ce que tu fais quand tu vas mal mais que personne ne le voit ?",
      "De quoi tu as besoin pour te sentir en sécurité financière ?",
      "Quelle période de ta vie aimerais-tu revivre une seule journée ?",
      "Quelle version passée de toi aurait le plus de mal à reconnaître qui tu es aujourd'hui ?",
      "Quelle version de toi te manque ?",
      "Est-ce qu'il faut parfois être égoïste pour être heureux ?",
      "Quelle personne as-tu peur de devenir ?",
      "Quel compliment tu as du mal à croire ?",
      "Quelle amitié t'a le plus fait évoluer ?",
      "Qu'est-ce que tu tolères alors que tu sais que tu ne devrais plus ?",
      "Quelle est ta priorité actuelle ?",
      "Quelle est ta plus grosse contradiction ?",
      "Est-ce que tu crois qu'on peut vraiment changer, assez pour mériter une seconde chance ?",
      "Qu'est-ce que tu aimerais désapprendre ou construire ?",
      "Qu'est-ce que tu refuses de sacrifier, même pour quelqu'un que tu aimes ?",
      "Quel événement de ta vie t'a probablement construit plus que tu ne le réalises ?",
      "Quel ami connaît une version de toi que presque personne d'autre ne connaît ?",
      "Quelle émotion as-tu le plus de mal à exprimer ?",
      "Qu'est-ce que tu envies facilement chez les autres ?",
      "Y a-t-il eu un moment dans ta vie où tu as réalisé que tu n'étais pas la personne que tu pensais être ?",
      "As-tu déjà vraiment détesté quelqu'un ? Pourquoi ?",
      "Quelle est la chose que tu aimerais faire avant de mourir mais que tu n'oses pas encore ?",
      "Quelle blessure influence encore ta manière d'aimer ?",
      "Oui ou non : s'associer à un ami ou à un membre de sa famille ?",
      "Est-ce que tu as davantage peur de mourir ou de ne pas avoir assez vécu ?",
      "Qu'est-ce que tu aimerais changer chez toi si tu savais que personne ne te jugerait ?",
      "Qu'est-ce qui te fait te sentir profondément en sécurité avec quelqu'un ?",
      "Quand est-ce que tu te sens le plus seul ?",
      "Quelle est ta définition de la réussite ?",
      "Quelle est la chose la plus courageuse que tu aies faite ?",
      "Quelle est la dernière chose qui t'a vraiment fait pleurer ?",
      "Quelle chose venant de ta famille aimerais-tu conserver toute ta vie ?",
      "Quel choix de vie as-tu fait principalement pour faire plaisir aux autres ?",
      "Tu as davantage peur d'échouer ou de réussir ?",
      "Quel souvenir peut te rendre instantanément nostalgique ?",
      "Quelle relation es-tu content d'avoir terminée ?",
      "Qu'est-ce qui te fait te sentir réellement vivant·e ?",
      "Si demain tu gagnes 100 M, est-ce que tu continues ce que tu fais aujourd'hui ? Et sinon, que changerais-tu ?",
      "Quelle est la plus grande leçon qu'une rupture ou une déception relationnelle t'a apprise ?",
      "Une omission volontaire, c'est un mensonge ?",
      "Quelle relation dans ta vie mériterait d'être différente ?",
      "C'est quoi le truc qui te semblait normal il y a quelques années et qu'aujourd'hui tu ne comprends pas ?",
      "Quel aspect de ta vie actuelle ne ressemble pas du tout à ce que tu imaginais ?",
      "Quel rôle as-tu naturellement pris dans ta famille ?",
      "Quelle est ta plus grosse insécurité aujourd'hui ?",
      "Si tu devais avoir une conversation de 4 h en tête-à-tête avec une personne présente, qui choisirais-tu ?",
      "Qu'est-ce que tu voudrais qu'on te dise plus souvent ?",
      "Quelle personne dans cette pièce te connaît le mieux ?",
      "Qu'est-ce que tu ne comprends toujours pas à ce jour ?",
      "Quelles identités portes-tu encore sans réussir à t'en détacher ? Une identité, pas une casquette qu'on enlève.",
      "Quelle chose tu ne feras jamais par peur du regard des autres ?",
      "Quelle chose sur toi serait la plus surprenante pour les gens ici ?",
      "Est-ce que tu pourrais être avec quelqu'un qui gagne énormément moins que toi ? Et énormément plus ?",
      "Qu'est-ce que tu sacrifies aujourd'hui pour ton ambition ?",
      "Qu'est-ce qui te fait perdre confiance en quelqu'un ?",
      "Si ta vie actuelle était un chapitre, quel serait son titre ?",
      "Si un membre de ta famille est « nocif » pour toi, tu romps la relation, ou le lien du sang passe avant tout et tu la préserves coûte que coûte ?",
      "Crois-tu à l'amour d'une vie ?",
      "Quel compliment te touche beaucoup plus qu'il ne devrait ?",
      "Quelle est la chose la plus difficile à reconnaître ou à accepter chez toi ?",
      "Qu'est-ce que le toi idéal a, que tu n'as pas encore ?",
      "Quel est le plus gros mensonge que tu te sois raconté à toi-même ?",
      "Tu préfères une vie stable ou une vie intense ?",
      "Quelle personne aimerais-tu mieux comprendre ?",
      "Si tu pouvais parler 10 minutes avec ton toi de 80 ans, quelle serait ta première question ?",
      "De quoi as-tu honte aujourd'hui ?",
      "Quelle personne a le plus changé ta manière de voir la vie ?",
      "Qu'est-ce que tu penses que les gens comprennent mal dans ta façon d'aimer ?",
      "De qui aimerais-tu secrètement obtenir davantage de reconnaissance ?",
      "Qu'est-ce que tu ne pardonnerais probablement jamais ?",
      "Quelle est pour toi la différence entre le lien amical et le lien amoureux ?",
      "Quel rêve as-tu abandonné trop vite ?",
      "Quelle dépense regrettes-tu ?",
      "Est-ce que tu te sens réellement heureux·se en ce moment ?",
      "Qu'est-ce que tu voudrais absolument avoir accompli dans 10 ans ?",
      "Quelle peur influence ta vie alors que tu en parles rarement ?",
      "Quelle est la chose la plus égoïste que tu aimerais faire un jour ?",
      "Quel comportement chez toi tu sais être un red flag ?",
      "Quelle est la chose que tu fais uniquement pour être validé·e ?",
      "Si ta vie reste exactement comme aujourd'hui pendant 5 ans, est-ce que ça te va ?",
      "Quelle vérité sur ta vie actuelle tu évites de regarder en face ?",
      "Quelle conversation aurais-tu aimé avoir avec quelqu'un avant qu'il ne sorte de ta vie ?",
      "Quelle relation t'a appris le plus sur tes propres limites ?",
      "Est-ce que tu crois à l'amitié homme-femme ?",
      "Qu'est-ce que tu cherches encore à prouver, et à qui ?",
      "Quelle opinion morale que tu avais très forte est devenue beaucoup plus nuancée avec l'âge ?",
      "Est-ce que tu préfères être respecté·e, admiré·e ou aimé·e ?",
      "Qu'est-ce qui te fait perdre confiance en toi ?",
      "Peut-on tout pardonner ?",
      "Est-ce que tu attends de ton partenaire de vie que ce soit ton meilleur ami ?",
      "Qu'est-ce qui te fait te sentir seul·e même quand tu es entouré·e ?",
      "Quelle partie de ton avenir te fait le plus peur ?",
      "Quelle décision penses-tu avoir prise trop tard ?",
      "Dans les participants actuels que tu ne connais pas, avec qui as-tu eu un fit particulier ?",
      "Quelle qualité chez toi est la plus difficile à voir pour toi-même ?",
      "Tu penses être facile ou difficile à aimer ?",
      "Quelle est la chose que tu refuses de devenir, même si elle te permettait de réussir davantage ?",
      "Est-ce que tu te sens compris par ton entourage ?",
      "Quand est-ce que tu te sens le plus toi-même ?",
      "Si tu savais que tu ne pouvais pas échouer, qu'est-ce que tu tenterais demain ?",
      "Tu préfères être quitté ou devoir quitter quelqu'un ?",
      "Est-ce que tu préférerais savoir que ton partenaire fantasme sur quelqu'un que vous connaissez, ou ne jamais le savoir ?"
    ]
  },

  crousti: {
    label: "Crousti",
    tagline: "Là, on ne fait plus semblant.",
    questions: [
      "Ta pire expérience flirt ou dating ?",
      "Quelle est la personne avec qui tu as eu la meilleure tension sexuelle ?",
      "Qui ici t'a fait une mauvaise première impression, et finalement une bonne surprise ?",
      "Quel est ton plus gros turn-off ?",
      "Quel est le flirt le plus mémorable que tu aies vécu ?",
      "Quel détail physique étonnamment précis peut te faire craquer ?",
      "Tu as déjà regretté de ne pas avoir tenté quelque chose avec quelqu'un ?",
      "Quel est ton plus gros turn-on ?",
      "Est-ce que tu pourrais regarder ton ou ta partenaire coucher avec quelqu'un d'autre ?",
      "Quelle est la première chose que tu remarques chez quelqu'un qui te plaît ?",
      "Le plus grand écart d'âge que tu as eu au lit ?",
      "Tu as déjà eu un crush sur quelqu'un qui était clairement une mauvaise idée ?",
      "Est-ce que tu préfères quelqu'un qui fait clairement comprendre son intérêt ou quelqu'un de mystérieux ?",
      "Quel est ton comportement le plus toxique quand tu as un crush ?",
      "Tu préfères ne faire que des plans à 3 jusqu'à la fin de ta vie, ou ne plus jamais coucher ?",
      "Tu as déjà embrassé quelqu'un que tu regrettais immédiatement ?",
      "Tu as déjà eu un crush sur un·e ami·e ?",
      "Entre la personne à ta gauche et celle à ta droite, qui a le plus de chances de te voir nu un jour ?",
      "Quelle est la pire manière de te faire perdre toute attirance ?",
      "Tu préfères qu'on ait accès à ton historique IA ou à ton historique porno ?",
      "Tu préfères séduire ou être séduit·e ?",
      "Quelle est la plus grosse différence entre ton type « sur le papier » et les personnes qui t'attirent réellement ?",
      "Qui ici t'a fait la meilleure première impression ?",
      "Tu as déjà développé des sentiments alors que tu avais dit que ça n'arriverait pas ?",
      "Quelle personnalité te rend irrémédiablement attiré·e ?",
      "Tu te considères plus vanille ou plus kinky que les gens présents ici ?",
      "Quel est ton plus gros red flag quand toi, tu es amoureux·se ?",
      "Tu préfères tromper une fois sans jamais être découvert, ou être trompé une fois sans jamais le savoir ?",
      "Est-ce que tu peux coucher avec quelqu'un sans avoir de sentiments ?",
      "Quelles sont tes meilleures techniques pour faire monter la tension sexuelle ?",
      "Quelle importance réelle donnerais-tu au sexe dans la réussite d'un couple, sur 10 ?",
      "Tu as déjà entretenu volontairement une tension avec quelqu'un sans avoir l'intention d'aller plus loin ?",
      "Tu pourrais tomber amoureux·se de quelqu'un sans être sexuellement attiré·e ?",
      "Pour ou contre l'ouverture du couple ?",
      "Quel est le date le plus catastrophique que tu aies vécu ?",
      "Tu préfères ne plus jamais coucher deux fois avec la même personne, ou n'en avoir qu'une seule jusqu'à la fin de ta vie ?",
      "Quel est le type de crush que tu assumes moins ?",
      "Quelle est la chose la plus attirante qu'une personne puisse faire par message ?",
      "Qui ici gère ton argent pendant un mois, qui gère tes dates, et qui prend tes décisions pro ?",
      "Tu as déjà eu une attirance que tu as gardée secrète pendant des mois ?",
      "Tu préfères une relation ultra passionnelle ou ultra stable ?",
      "Quel est le signe qui te fait comprendre qu'un flirt va probablement devenir sérieux ?",
      "Entre la personne à ta gauche et celle à ta droite, avec qui tu pars en vacances, et avec qui tu montes un business ?",
      "Tu préfères quelqu'un de dominant dans la séduction ou quelqu'un qui te laisse mener ?",
      "Quelle est la chose la plus spontanée que tu aies faite par attirance ?",
      "Est-ce que sucer c'est tromper ?",
      "Tu as déjà embrassé quelqu'un sans vraiment savoir si tu en avais envie ?",
      "Tu as déjà envoyé un nude que tu regrettes ?",
      "Quel est ton pire move de stalk ?",
      "Quel est ton plus gros « ça aurait pu être quelque chose » ou « et si ? » amoureux ?",
      "Quelle importance donnes-tu à la fréquence dans une relation ?",
      "Tu préfères une relation où il y a énormément de désir ou énormément de complicité ?",
      "Quelle est la pire excuse que tu as utilisée pour voir quelqu'un ?",
      "Qui ici a le plus de charme indépendamment du physique ?",
      "Quelle est la plus grosse folie que tu aies faite pour voir ou revoir quelqu'un ?",
      "Est-ce que le bodycount de quelqu'un peut changer le regard que tu portes sur lui ou elle ? Si oui, à partir de quand ?",
      "Tu préfères le flirt innocent ou la tension qui devient insoutenable ?",
      "Tu as déjà fait exprès de rendre quelqu'un jaloux ?",
      "L'endroit le plus insolite où tu as ken ?",
      "Quelle personne de ton passé pourrait encore te faire perdre tes moyens ?",
      "Quel est le truc le plus sexy qu'une personne puisse faire sans te toucher ?",
      "Est-ce que pour toi sucer est plus intime qu'une pénétration ?",
      "Quel est le moment où tu sais que tu as vraiment envie d'embrasser quelqu'un ?",
      "Entre la personne à ta gauche et celle à ta droite, qui a probablement les kinks les plus inattendus ?",
      "Tu as déjà eu une attirance pour deux personnes en même temps ?",
      "Quel est ton fantasme romantique plutôt que sexuel ?",
      "Quel kink te plairait probablement, mais que tu n'as jamais testé ?",
      "Quel est le pire « situationship » de ta vie ?",
      "Quelle est la chose la plus gênante que tu aies faite devant quelqu'un qui te plaisait ?",
      "Quelle est la chose la plus risquée que tu serais prêt·e à faire pour un crush ?",
      "Tu préfères une vie sexuelle incroyable sans jamais tomber amoureux, ou un amour profond avec une vie sexuelle médiocre ?",
      "Tu préfères tomber amoureux·se progressivement ou avoir le coup de foudre ?",
      "Sur un curseur de 1 à 10, 1 étant « homo » et 10 « hétéro », comment situerais-tu ton orientation sexuelle ?",
      "Qui dans cette pièce aurait le plus de chances de te faire craquer ?",
      "Quel est le meilleur mensonge que tu as raconté pour cacher ton attirance pour quelqu'un ?",
      "Est-ce que tu as déjà flirté avec quelqu'un uniquement pour l'ego ?",
      "Si tu pouvais revivre un seul flirt de ta vie, lequel ?",
      "Quel ex te ferait le plus d'effet en revenant demain ?",
      "Pour ou contre les jeux de rôles ?",
      "Qui est la personne avec qui tu as le plus de chances de perdre toute rationalité ?",
      "Avec combien de personnes présentes ici tu pourrais coucher ?"
    ]
  }

};
